# Generated by Django 2.1.5 on 2019-03-27 08:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0034_auto_20190323_1700'),
    ]

    operations = [
        migrations.CreateModel(
            name='Watch_List',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='None', max_length=100)),
                ('company_list', models.CharField(default='', max_length=300)),
            ],
        ),
    ]
