# Generated by Django 2.1.5 on 2019-04-09 07:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0035_watch_list'),
    ]

    operations = [
        migrations.AddField(
            model_name='strategy_group',
            name='entry_condition',
            field=models.CharField(default='Buy', max_length=200),
        ),
    ]
