# Generated by Django 2.1.5 on 2019-04-09 11:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0036_strategy_group_entry_condition'),
    ]

    operations = [
        migrations.AddField(
            model_name='strategy_group',
            name='instrument',
            field=models.CharField(default='884737', max_length=100),
        ),
        migrations.AlterField(
            model_name='strategy',
            name='instrument',
            field=models.CharField(default='884737', max_length=100),
        ),
    ]
