# Generated by Django 2.1.5 on 2019-04-09 11:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0037_auto_20190409_1650'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='strategy_group',
            name='instrument',
        ),
        migrations.AddField(
            model_name='strategy_group',
            name='comp_name',
            field=models.CharField(default='NONE', max_length=100),
        ),
    ]
